### PR TITLE
set_fs() is being deprecated in 5.10

### PR DESCRIPTION
**Pull request by rkakrik**
Find solution in https://github.com/gnab/rtl8812au/pull/213

### CODE REVIEW

**Comment by McMCCRU** [comment]
Hi!
This can break the assembly with old kernels, maybe it makes sense to take these insert through #ifdef for checking with kernel 5.10 and higher?

**Comment by rkakrik** [comment]
> Hi!
> This can break the assembly with old kernels, maybe it makes sense to take these insert through #ifdef for checking with kernel 5.10 and higher?

I think kernel_read() should work since at least 4.14 kernel. I checked build with 5.4.86-1-lts.

**Comment by McMCCRU** [comment]
I checked build my project with kernel 2.6.27.55.....
igor@igor-GL553VE:~/Trunk/TEST/rtl8188gu$ LANG=C make
make ARCH=csky CROSS_COMPILE=/opt/goxceed/csky-linux-tools-i386-uclibc-20170724/bin/csky-linux- -C /home/igor/Build_GX2/buildroot/kernel/2.6.27.55 M=/home/igor/Trunk/TEST/rtl8188gu  modules
make[1]: Entering directory '/home/igor/Build_GX2/buildroot/kernel/2.6.27.55'
  CC [M]  /home/igor/Trunk/TEST/rtl8188gu/os_dep/osdep_service.o
/home/igor/Trunk/TEST/rtl8188gu/os_dep/osdep_service.c: In function 'isFileReadable':
/home/igor/Trunk/TEST/rtl8188gu/os_dep/osdep_service.c:2095:3: warning: passing argument 2 of 'kernel_read' makes integer from pointer without a cast
include/linux/fs.h:1812:12: note: expected 'long unsigned int' but argument is of type 'char *'
/home/igor/Trunk/TEST/rtl8188gu/os_dep/osdep_service.c:2095:3: warning: passing argument 3 of 'kernel_read' makes pointer from integer without a cast
include/linux/fs.h:1812:12: note: expected 'char *' but argument is of type 'int'
/home/igor/Trunk/TEST/rtl8188gu/os_dep/osdep_service.c:2095:3: warning: passing argument 4 of 'kernel_read' makes integer from pointer without a cast
include/linux/fs.h:1812:12: note: expected 'long unsigned int' but argument is of type 'void *'
/home/igor/Trunk/TEST/rtl8188gu/os_dep/osdep_service.c: In function 'retriveFromFile':
/home/igor/Trunk/TEST/rtl8188gu/os_dep/osdep_service.c:2119:4: warning: passing argument 2 of 'kernel_read' makes integer from pointer without a cast
include/linux/fs.h:1812:12: note: expected 'long unsigned int' but argument is of type 'u8 *'
/home/igor/Trunk/TEST/rtl8188gu/os_dep/osdep_service.c:2119:4: warning: passing argument 3 of 'kernel_read' makes pointer from integer without a cast
include/linux/fs.h:1812:12: note: expected 'char *' but argument is of type 'u32'
/home/igor/Trunk/TEST/rtl8188gu/os_dep/osdep_service.c:2119:4: warning: passing argument 4 of 'kernel_read' makes integer from pointer without a cast
include/linux/fs.h:1812:12: note: expected 'long unsigned int' but argument is of type 'void *'
/home/igor/Trunk/TEST/rtl8188gu/os_dep/osdep_service.c: In function 'storeToFile':
/home/igor/Trunk/TEST/rtl8188gu/os_dep/osdep_service.c:2151:4: error: implicit declaration of function 'kernel_write'
make[2]: *** [scripts/Makefile.build:214: /home/igor/Trunk/TEST/rtl8188gu/os_dep/osdep_service.o] Error 1
make[1]: *** [Makefile:1380: _module_/home/igor/Trunk/TEST/rtl8188gu] Error 2
make[1]: Leaving directory '/home/igor/Build_GX2/buildroot/kernel/2.6.27.55'
make: *** [Makefile:1913: modules] Error 2

**Comment by McMCCRU** [comment]
igor@igor-GL553VE:~/Trunk/TEST/rtl8188gu$ patch -R -p1 < 3.patch 
patching file os_dep/osdep_service.c
igor@igor-GL553VE:~/Trunk/TEST/rtl8188gu$ LANG=C make
make ARCH=csky CROSS_COMPILE=/opt/goxceed/csky-linux-tools-i386-uclibc-20170724/bin/csky-linux- -C /home/igor/Build_GX2/buildroot/kernel/2.6.27.55 M=/home/igor/Trunk/TEST/rtl8188gu  modules
make[1]: Entering directory '/home/igor/Build_GX2/buildroot/kernel/2.6.27.55'
  CC [M]  /home/igor/Trunk/TEST/rtl8188gu/os_dep/osdep_service.o
  CC [M]  /home/igor/Trunk/TEST/rtl8188gu/os_dep/linux/os_intfs.o
  CC [M]  /home/igor/Trunk/TEST/rtl8188gu/os_dep/linux/usb_intf.o

**Comment by McMCCRU** [comment]
I another accepted another fix, does not break driver build on older kernels.

**Comment by Simple2ich4n** [comment]
I used to install on the VM Kali-Linux, after compiling and installing, the system will crash, I don’t know what to do？

**Pull request closed without merging**
